apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zpq3py470-python 
  janus-idp.io/tekton: zpq3py470-python
  backstage.io/kubernetes-id: zpq3py470-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zpq3py470-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml